batch_size: 4
eval_batch_size: 4
dropout: 0.15
lr: 0.001
num_layers: 7
JK : "none"
task_names:
  - "arxiv_fs"
  - "FB15K237_fs"
  - "chemblpre"

d_multiple:
  - 10
  - 10
  - 0.5

d_min_ratio:
  - 5
  - 5
  - 0.5
