E2E-node: &E2E-node
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

arxiv: &arxiv
  <<: *E2E-node
  dataset: arxiv

cora_node: &cora_node
  <<: *E2E-node
  dataset: cora_node

pubmed_node: &pubmed_node
  <<: *E2E-node
  dataset: pubmed_node

wikics: &wikics
  <<: *E2E-node
  dataset: wikics

logic_arxiv:
  <<: *E2E-node
  dataset: logic_arxiv
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: logic_arxiv
    - stage: valid
      split_name: valid
      dataset: logic_cora
    - stage: test
      split_name: test
      dataset: logic_cora
    - stage: test
      split_name: train
      dataset: logic_cora

logic_cora:
  <<: *E2E-node
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: cora_node
    - stage: valid
      split_name: valid
      dataset: cora_node
    - stage: valid
      split_name: valid
      dataset: logic_cora
    - stage: test
      split_name: test
      dataset: logic_cora
    - stage: test
      split_name: train
      dataset: logic_cora

E2E-link: &E2E-link
  eval_pool_mode: mean
  task_level: e2e_link

cora_link: &cora_link
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: cora_link
    - stage: valid
      split_name: valid
      dataset: cora_link_eval
    - stage: valid
      split_name: valid
      dataset: cora_node
    - stage: test
      split_name: test
      dataset: cora_link_eval
    - stage: test
      split_name: train
      dataset: cora_link

pubmed_link: &pubmed_link
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: pubmed_link
    - stage: valid
      split_name: valid
      dataset: pubmed_link_eval
    - stage: test
      split_name: test
      dataset: pubmed_link_eval
    - stage: test
      split_name: train
      dataset: pubmed_link

FB15K237: &FB15K237
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: FB15K237
    - stage: valid
      split_name: valid
      dataset: FB15K237_eval
    - stage: test
      split_name: test
      dataset: FB15K237_eval
    - stage: test
      split_name: train
      dataset: FB15K237

WN18RR: &WN18RR
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: WN18RR
    - stage: valid
      split_name: valid
      dataset: WN18RR_eval
    - stage: test
      split_name: test
      dataset: WN18RR_eval
    - stage: test
      split_name: train
      dataset: WN18RR

E2E-graph: &E2E-graph
  task_level: e2e_graph
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

chemblpre: &chemblpre
  <<: *E2E-graph
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: chemblpre
    - stage: valid
      split_name: valid
      dataset: chempcba_eval
    - stage: valid
      split_name: valid
      dataset: chemhiv
    - stage: test
      split_name: test
      dataset: chemhiv

chempcba: &chempcba
  <<: *E2E-graph
  train: chempcba
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: chempcba
    - stage: valid
      split_name: valid
      dataset: chempcba_eval
    - stage: test
      split_name: test
      dataset: chempcba_eval
    - stage: test
      split_name: train
      dataset: chempcba

chemhiv: &chemhiv
  <<: *E2E-graph
  dataset: chemhiv


LR-node: &LR-node
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

arxiv_fs: &arxiv_fs
  <<: *LR-node
  dataset: arxiv_fs
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: arxiv_fs
    - stage: valid
      split_name: valid
      dataset: arxiv_fs_51
    - stage: valid
      split_name: valid
      dataset: arxiv_fs_53
    - stage: valid
      split_name: valid
      dataset: arxiv_fs_55
    - stage: valid
      split_name: valid
      dataset: cora_fs_21
    - stage: valid
      split_name: valid
      dataset: cora_fs_23
    - stage: valid
      split_name: valid
      dataset: cora_fs_25
    - stage: valid
      split_name: valid
      dataset: cora_fs_71
    - stage: valid
      split_name: valid
      dataset: cora_fs_73
    - stage: valid
      split_name: valid
      dataset: cora_fs_75
    - stage: test
      split_name: test
      dataset: arxiv_fs_51
    - stage: test
      split_name: test
      dataset: arxiv_fs_53
    - stage: test
      split_name: test
      dataset: arxiv_fs_55
    - stage: test
      split_name: test
      dataset: cora_fs_21
    - stage: test
      split_name: test
      dataset: cora_fs_23
    - stage: test
      split_name: test
      dataset: cora_fs_25
    - stage: test
      split_name: test
      dataset: cora_fs_71
    - stage: test
      split_name: test
      dataset: cora_fs_73
    - stage: test
      split_name: test
      dataset: cora_fs_75

LR-link: &LR-link
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

FB15K237_fs: &FB15K237_fs
  <<: *LR-link
  dataset: FB15K237_fs
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: FB15K237_fs
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_101
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_103
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_105
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_201
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_203
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_205
    - stage: valid
      split_name: valid
      dataset: WN18RR_fs_51
    - stage: valid
      split_name: valid
      dataset: WN18RR_fs_53
    - stage: valid
      split_name: valid
      dataset: WN18RR_fs_55
    - stage: test
      split_name: test
      dataset: FB15K237_fs_101
    - stage: test
      split_name: test
      dataset: FB15K237_fs_103
    - stage: test
      split_name: test
      dataset: FB15K237_fs_105
    - stage: test
      split_name: test
      dataset: FB15K237_fs_201
    - stage: test
      split_name: test
      dataset: FB15K237_fs_203
    - stage: test
      split_name: test
      dataset: FB15K237_fs_205
    - stage: test
      split_name: test
      dataset: WN18RR_fs_51
    - stage: test
      split_name: test
      dataset: WN18RR_fs_53
    - stage: test
      split_name: test
      dataset: WN18RR_fs_55
